# .github/workflows/test.yml
name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: |
            node_modules
            ~/.cache/Cypress
      
      - run: npm ci
      # Install Testmo CLI tool locally (then use npx testmo .. to run it)
      - run: npm install --no-save @testmo/testmo-cli
      - run: npx cypress run

      # Optionally add a couple of fields such as the git hash and link to the build
      - run: |
          npx testmo automation:resources:add-field --name git --type string \
            --value ${GITHUB_SHA:0:7} --resources resources.json
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          npx testmo automation:resources:add-link --name build \
            --url $RUN_URL --resources resources.json
      
      - run: |
          if [[ -z "${TESTMO_URL}" ]]; then
            echo "The TESTMO_URL secret is not defined for this repository"
            exit 1
          fi

          if [[ -z "${TESTMO_TOKEN}" ]]; then
            echo "The TESTMO_TOKEN secret is not defined for this repository"
            exit 1
          fi
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

      # Run automated tests and report results to Testmo
      - run: |
          npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Test run" \
            --source "CICD" \
            --resources resources.json \
            --results results/*.xml
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
